### ISSUE TITLE
Username/pseud invisible/black until mousover

### ISSUE THREAD

**Issue by deusexcalamus** [cicerakes/DarkNight-AO3#1] opened 2020-04-23 05:02 UTC
Firefox 75
Happens on any Ao3 page

As subject says, pseud/username at top right is black/hard to see until mouseover, see attached screenshot
![image](https://user-images.githubusercontent.com/8674645/80061041-b2cf3780-84f5-11ea-9a5c-3d8c0818a079.png)

**Comment by cicerakes** [comment] 2020-04-23 07:23
I can't reproduce this in Firefox 75. 

Have you tried updating the style to the latest version? It should be v1.3.0.

**Comment by deusexcalamus** [comment] 2020-04-23 07:25
> 
> 
> I can't reproduce this in Firefox 75.
> 
> Have you tried updating the style to the latest version? It should be v1.3.0.

I'll poke at it. I'm also running some 'custom' stuff too that might mess with it.

**Comment by deusexcalamus** [comment] 2020-04-23 07:27
It's another addon. I'm investigating.

**Comment by deusexcalamus** [comment] 2020-04-23 07:34
Ok, I was wrong. It's not an addon. In order for my username to be visible at the top right, I have to have the 'reversi' site skin set, setting it to anything else reproduces the isse.

**Comment by cicerakes** [comment] 2020-04-23 07:42
I have no site skins set, but still can't reproduce the issue. 

Just to check, are you using the style found on userstyles.org, or the one found here on GitHub?

**Comment by deusexcalamus** [comment] 2020-04-23 07:44
using the github one. If you need any specific info, let me know, I'm not afraid to get down and dirty. :)

**Comment by cicerakes** [comment] 2020-04-23 07:54
Well, I'm not completely sure what's causing the issue, but I've pushed an update that _should_ fix it... theoretically.

Let me know if it works.

**Comment by deusexcalamus** [comment] 2020-04-23 07:58
That's got it. What was the issue?

**Comment by cicerakes** [comment] 2020-04-23 08:07
In the past I've found that sometimes Firefox has issues with applying styles when the properties weren't set to `!important`.

So this issue was fixed by adding `!important` to the text colour property for usernames.

**Comment by deusexcalamus** [comment] 2020-04-23 08:08
yeah I saw it when I looked at the code change. You can go ahead and close this. Thanks for the help :)

**Closed as completed** 2020-04-23 08:08 UTC
Labels: bug
